apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: spring-deployment 
spec: 
  selector: 
    matchLabels: 
      app: spring 
  replicas: 3
  template:
    metadata: 
      labels: 
        app: spring 
    spec: 
      containers: 
      - name: spring
        image: sooabia/spring-reactor-redis:#{Build.BuildId}#
        ports: 
        - containerPort: 8080 
      - name: redis 
        image: redis:4.0.8-alpine
        ports: 
        - containerPort: 6379
---  
kind: Service 
apiVersion: v1 
metadata: 
  name: spring-service 
spec: 
  selector: 
    app: spring 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080
  type: LoadBalancer
